name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install required packages
      run: |
        pip3 install -r docs/requirements.txt
        # the sphinx-c-autodoc library keeps throwing an error on
        # first run. if you reinstall libclang, this problem disappears.
        # that's why we have to build once
        sphinx-build docs /tmp || true
        pip3 install --force $(cat docs/requirements.txt | grep ^libclang)

    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        publish: false

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}
