name: Github Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install required packages
      run: |
        python3 -m pip install -r docs/requirements.txt
        # the sphinx-c-autodoc library keeps throwing an error on
        # first run. if you reinstall libclang, this problem disappears.
        # that's why we have to build once
        sphinx-build docs /tmp || true
        python3 -m pip install --force $(cat docs/requirements.txt | grep ^libclang)

    - id: build
      uses: sphinx-notes/pages@v3
      with:
        publish: false

    - name: Deploy to pages
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.build.outputs.artifact }}
